### ISSUE TITLE
extensionless no longer available?

### ISSUE THREAD

**Issue by aae42** [olsonpm/sqlite-to-rest#7]
getting this when trying to install:

```
❯ npm install --global olsonpm/sqlite-to-rest#dev
npm ERR! code ENOVERSIONS
npm ERR! No versions available for extensionless
```
not a node expert by any means but can't seem to install extensionless:
```
❯ npm i extensionless
npm ERR! code ENOVERSIONS
npm ERR! No versions available for extensionless
```
seems it might be gone now?
https://github.com/ifyio/extensionless
```

**Comment by olsonpm** [comment]
hey thanks for raising this issue.  i should have time tomorrow to fix.

**Comment by olsonpm** [comment]
@aae42 alright the newest commit fixes this.  Seems extensionless wasn't even used, so that's bad on my part heh.

I also had to update the sqlite3 dependency since sqlite3 v4 wasn't building for node v16.

Anyway the tests pass and I ran through the tutorial, seems to work.  Let me know if you run into issues.
